export default {
    "China": "China",
    "United States": '\"United States\"',
    "United Kingdom": '\"United Kingdom\"',
    "Germany": "Germany",
    "Canada": "Canada",
    "Japan": "Japan",
    "Australia": "Australia",
    "France": "France",
    "Hong Kong": '\"Hong Kong\"',
    "Italy": "Italy",
    "South Korea": '\"South Korea\"',
    "Spain": "Spain",
    "Taiwan": "Taiwan",
    "Switzerland": "Switzerland",
    "Netherlands": "Netherlands",
    "Russian Federation": '\"Russian Federation\"',
    "India": "India",
    "Brazil": "Brazil",
    "Sweden": "Sweden",
    "Singapore": "Singapore",
    "Poland": "Poland",
    "Austria": "Austria",
    "Denmark": "Denmark",
    "Belgium": "Belgium",
    "Czech Republic": '\"Czech Republic\"',
    "Finland": "Finland",
    "Turkey": "Turkey",
    "Greece": "Greece",
    "Israel": "Israel",
    "Norway": "Norway",
    "Mexico": "Mexico",
    "South Africa": '\"South Africa\"',
    "Saudi Arabia": '\"Saudi Arabia\"',
    "Hungary": "Hungary",
    "Portugal": "Portugal",
    "Pakistan": "Pakistan",
    "Colombia": "Colombia",
    "Ireland": "Ireland",
    "New Zealand": '\"New Zealand\"',
    "Chile": "Chile",
    "Romania": "Romania",
    "Thailand": "Thailand",
    "Argentina": "Argentina",
    "Malaysia": "Malaysia",
    "Iran": "Iran",
    "Egypt": "Egypt",
    "Ukraine": "Ukraine",
    "Serbia": "Serbia",
    "Armenia": "Armenia",
    "Georgia": "Georgia",
    "Slovenia": "Slovenia",
    "Croatia": "Croatia",
    "Bulgaria": "Bulgaria",
    "Belarus": "Belarus",
    "Slovakia": "Slovakia",
    "Macao": "Macao",
    "Estonia": "Estonia",
    "Cyprus": "Cyprus",
    "Viet Nam": '\"Viet Nam\"',
    "Qatar": "Qatar",
    "Lithuania": "Lithuania",
    "Morocco": "Morocco",
    "Ecuador": "Ecuador",
    "Philippines": "Philippines",
    "United Arab Emirates": '\"United Arab Emirates\"',
    "Azerbaijan": "Azerbaijan",
    "Peru": "Peru",
    "Sri Lanka": '\"Sri Lanka\"',
    "Indonesia": "Indonesia",
    "Nigeria": "Nigeria",
    "Latvia": "Latvia",
    "Kenya": "Kenya",
    "Bangladesh": "Bangladesh",
    "Lebanon": "Lebanon",
    "Cuba": "Cuba",
    "Puerto Rico": '\"Puerto Rico\"',
    "Nepal": "Nepal",
    "Iceland": "Iceland",
    "Ghana": "Ghana",
    "Mongolia": "Mongolia",
    "Jordan": "Jordan",
    "Algeria": "Algeria",
    "Tunisia": "Tunisia",
    "Ethiopia": "Ethiopia",
    "Palestine": "Palestine",
    "Kuwait": "Kuwait",
    "Uganda": "Uganda",
    "Uruguay": "Uruguay",
    "Iraq": "Iraq",
    "Luxembourg": "Luxembourg",
    "Kazakhstan": "Kazakhstan",
    "Panama": "Panama",
    "Venezuela": "Venezuela",
    "Oman": "Oman",
    "Costa Rica": '\"Costa Rica\"',
    "Cameroon": "Cameroon",
    "Tanzania": "Tanzania",
    "Uzbekistan": "Uzbekistan",
    "Montenegro": "Montenegro",
    "Myanmar": "Myanmar",
    "North Macedonia": '\"North Macedonia\"',
    "Sudan": "Sudan",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
    "Rwanda": "Rwanda",
    "Senegal": "Senegal",
    "Malta": "Malta",
    "Cambodia": "Cambodia",
    "Benin": "Benin",
    "Kyrgyzstan": "Kyrgyzstan",
    "Mozambique": "Mozambique",
    "Bahrain": "Bahrain",
    "Cote d'Ivoire": '\"Cote d\'Ivoire\"',
    "Bolivia": "Bolivia",
    "Brunei Darussalam": '\"Brunei Darussalam\"',
    "Malawi": "Malawi",
    "Monaco": "Monaco",
    "Paraguay": "Paraguay",
    "Honduras": "Honduras",
    "Botswana": "Botswana",
    "Congo": "Congo",
    "Bosnia and Herzegovina": '\"Bosnia and Herzegovina\"',
    "Guatemala": "Guatemala",
    "Madagascar": "Madagascar",
    "Jamaica": "Jamaica",
    "Yemen": "Yemen",
    "Mauritius": "Mauritius",
    "Fiji": "Fiji",
    "Laos": "Laos",
    "Namibia": "Namibia",
    "Albania": "Albania",
    "Moldova": "Moldova",
    "Papua New Guinea": '\"Papua New Guinea\"',
    "Libyan Arab Jamahiriya": '\"Libyan Arab Jamahiriya\"',
    "Trinidad and Tobago": '\"Trinidad and Tobago\"',
    "Burkina Faso": '\"Burkina Faso\"',
    "Democratic Republic Congo": '\"Democratic Republic Congo\"',
    "Syrian Arab Republic": '\"Syrian Arab Republic\"',
    "Bhutan": "Bhutan",
    "Federated States of Micronesia": '\"Federated States of Micronesia\"',
    "Dominican Republic": '\"Dominican Republic\"',
    "New Caledonia": '\"New Caledonia\"',
    "Gambia": "Gambia",
    "Mali": "Mali",
    "Barbados": "Barbados",
    "Afghanistan": "Afghanistan",
    "Tajikistan": "Tajikistan",
    "Saint Kitts and Nevis": '\"Saint Kitts and Nevis\"',
    "Sierra Leone": '\"Sierra Leone\"',
    "Niger": "Niger",
    "Gabon": "Gabon",
    "Anguilla": "Anguilla",
    "Togo": "Togo",
    "El Salvador": '\"El Salvador\"',
    "Liberia": "Liberia",
    "Haiti": "Haiti",
    "Seychelles": "Seychelles",
    "Grenada": "Grenada",
    "Guam": "Guam",
    "Nicaragua": "Nicaragua",
    "North Korea": '\"North Korea\"',
    "Eritrea": "Eritrea",
    "Bahamas": "Bahamas",
    "Bermuda": "Bermuda",
    "Comoros": "Comoros",
    "Guinea": "Guinea",
    "Saint Vincent and the Grenadines": '\"Saint Vincent and the Grenadines\"',
    "American Samoa": '\"American Samoa\"',
    "Burundi": "Burundi",
    "Dominica": "Dominica",
    "Guyana": "Guyana",
    "Curaçao": "Curaçao",
    "Equatorial Guinea": '\"Equatorial Guinea\"',
    "Guadeloupe": "Guadeloupe",
    "Lesotho": "Lesotho",
    "Macedonia": "Macedonia",
    "Netherlands Antilles": '\"Netherlands Antilles\"',
    "Samoa": "Samoa",
    "Somalia": "Somalia",
    "Turkmenistan": "Turkmenistan",
    "Virgin Islands (U.S.)": '\"Virgin Islands (U.S.)\"',
    "Yugoslavia": "Yugoslavia",
}